workflows:
  unity-ios-workflow:
    name: unity_ios_workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: me.kokecacao.swingsimulator
      groups:
        - unity_credentials
      vars:
        BUILD_SCRIPT: BuildIos
        UNITY_IOS_DIR: Build
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        APP_STORE_APP_ID: 1671675115
      cocoapods: default
    scripts:
      - name: Activate Unity License
        script: |
          LOG_FILE=unity.log
          touch ${LOG_FILE}
          $UNITY_HOME/Contents/MacOS/Unity -quit -batchmode -nographics -logFile ${LOG_FILE} \
            -serial ${UNITY_SERIAL} \
            -username ${UNITY_EMAIL} \
            -password ${UNITY_PASSWORD}
          cat ./unity.log
      - name: Generate the Xcode project from Unity
        script: |
          LOG_FILE=unity.log
          $UNITY_HOME/Contents/MacOS/Unity -batchmode \
            -quit \
            -logFile ${LOG_FILE} \
            -projectPath . \
            -executeMethod BuildScript.$BUILD_SCRIPT \
            -nographics \
            -serial ${UNITY_SERIAL} \
            -username ${UNITY_EMAIL} \
            -password ${UNITY_PASSWORD}
          echo "unity returned code $?. here is log file:"
          cat ${LOG_FILE}
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          BUILD_NUMBER=($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID") + 1)
          echo "incrementing build number to $BUILD_NUMBER"
          echo "current directory at ${PWD} contains folder:"
          ls -la
          cd $UNITY_IOS_DIR && agvtool new-version -all $BUILD_NUMBER && echo "success!" || echo "failed! will not increment build number"
      - name: Build ipa for distribution
        script: |
          echo "current directory at ${PWD} contains folder:"
          ls -la
          xcode-project build-ipa \
            --project "$UNITY_IOS_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      scripts:
        - name: Deactivate Unity License
          script: | 
            /Applications/Unity\ Hub.app/Contents/Frameworks/UnityLicensingClient_V1.app/Contents/MacOS/Unity.Licensing.Client \
            --return-ulf \
            --username ${UNITY_EMAIL} \
            --password ${UNITY_PASSWORD}
            rm -rf "/Library/Application Support/Unity/Unity_lic.ulf"
      email:
        recipients:
          - su.chen.hanke@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        #
        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true 
        #
        # Specify the names of beta tester groups that will get access 
        # to the build once it has passed beta review.
        beta_groups:
          - group
        #
        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false